INFO     test_case:conftest.py:56 cap info: {'platformName': 'Android', 'automationName': 'UiAutomator2', 'platformVersion': '11', 'deviceName': 'c543cf80', 'appActivity': 'com.mega.carsettings.CarSettingActivity', 'appPackage': 'com.mega.carsettings'}
INFO     test_case:conftest.py:72 启动app参数为: {'platformName': 'Android', 'automationName': 'UiAutomator2', 'platformVersion': '11', 'deviceName': 'c543cf80', 'appActivity': 'com.mega.carsettings.CarSettingActivity', 'appPackage': 'com.mega.carsettings'}
INFO     test_case:conftest.py:84 
    初始化wifi驱动
     成功
INFO     test_case:base_page.py:41 开始初始化驱动driver......
INFO     test_case:base_page.py:41 开始初始化驱动driver......
INFO     test_case:base_page.py:535 元素描述为: 连接按钮
INFO     test_case:base_page.py:543 web_elem: <appium.webdriver.webelement.WebElement (session="d7c8c09b-7dd4-4c93-ad3b-53668b65be33", element="040c972e-df2f-4f31-b5de-782acba0bea1")>
INFO     test_case:base_page.py:555 连接按钮 locator: ('id', 'com.mega.carsettings:id/menu_connect')
INFO     test_case:base_page.py:535 元素描述为: WIFI开关
INFO     test_case:base_page.py:543 web_elem: <appium.webdriver.webelement.WebElement (session="d7c8c09b-7dd4-4c93-ad3b-53668b65be33", element="c2546d27-8ae4-4eef-a42b-f9290ff3200a")>
INFO     test_case:base_page.py:555 WIFI开关 locator: ('id', 'android:id/switch_widget')
INFO     test_case:base_page.py:535 元素描述为: 进去wifi连接按钮
INFO     test_case:base_page.py:553 web_elem: <appium.webdriver.webelement.WebElement (session="d7c8c09b-7dd4-4c93-ad3b-53668b65be33", element="8a37aad7-ed71-4255-898f-6a0470cc4bda")>
INFO     test_case:base_page.py:555 进去wifi连接按钮 locator: ('id', 'com.mega.carsettings:id/iv_arrow')
INFO     test_case:base_page.py:133 wait_locator: ('xpath', '//android.widget.TextView[contains(@text, "AAAAA")]')
INFO     test_case:base_page.py:535 元素描述为: 密码输入框
ERROR    test_case:base_page.py:563 元素 密码输入框 的表达式 ('id', 'com.mega.carsettings:id/et_password_content') 未定位到: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:75:1)
    at /Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:92:1
    at flush (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/_microtask.js:18:1)
    at process._tickCallback (internal/process/next_tick.js:61:11)
INFO     test_case:base_page.py:566 错误截图为: /Users/yuxiang/PycharmProjects/chery_app_test/logs/imgs/2023-06-28-10-38-51.png
INFO     test_case:conftest.py:88 正在关闭驱动
INFO     test_case:conftest.py:90 关闭驱动成功！