INFO     test_case:conftest.py:55 cap info: {'platformName': 'Android', 'automationName': 'UiAutomator2', 'platformVersion': '11', 'deviceName': 'c543cf80', 'noReset': True, 'appActivity': 'com.mega.btphone.ui.BtPhoneActivity', 'appPackage': 'com.mega.btphone'}
INFO     test_case:conftest.py:64 启动app参数为: {'platformName': 'Android', 'automationName': 'UiAutomator2', 'platformVersion': '11', 'deviceName': 'c543cf80', 'noReset': True, 'appActivity': 'com.mega.btphone.ui.BtPhoneActivity', 'appPackage': 'com.mega.btphone'}
INFO     test_case:conftest.py:209 
    初始化蓝牙电话驱动
     成功
INFO     test_case:base_page.py:41 开始初始化驱动driver......
INFO     test_case:base_page.py:41 开始初始化驱动driver......
INFO     test_case:base_page.py:527 元素描述为: 获取连接蓝牙按钮
INFO     test_case:base_page.py:535 web_elem: <appium.webdriver.webelement.WebElement (session="96a97253-fc82-4018-96a3-12e7f8132934", element="d61a825c-af25-4e4d-82d6-5d4d0e27ffeb")>
INFO     test_case:base_page.py:547 获取连接蓝牙按钮 locator: ('id', 'com.mega.btphone:id/go_setting_in_disconnect')
INFO     test_case:base_page.py:527 元素描述为: 蓝牙开关按钮
INFO     test_case:base_page.py:535 web_elem: <appium.webdriver.webelement.WebElement (session="96a97253-fc82-4018-96a3-12e7f8132934", element="2314fba9-065d-4370-8c52-9bc414ecb647")>
INFO     test_case:base_page.py:547 蓝牙开关按钮 locator: ('id', 'android:id/switch_widget')
INFO     test_case:test_btphone.py:63 蓝牙开关属性为: true
INFO     test_case:test_btphone.py:67 蓝牙已打开
INFO     test_case:base_page.py:527 元素描述为: 连接设备历史
INFO     test_case:base_page.py:535 web_elem: <appium.webdriver.webelement.WebElement (session="96a97253-fc82-4018-96a3-12e7f8132934", element="b551c6b8-c96a-45a6-951b-10804e20abff")>
INFO     test_case:base_page.py:547 连接设备历史 locator: ('id', 'com.mega.carsettings:id/iv_arrow')
INFO     test_case:base_page.py:527 元素描述为: 连接设备id
INFO     test_case:base_page.py:545 web_elem: <appium.webdriver.webelement.WebElement (session="96a97253-fc82-4018-96a3-12e7f8132934", element="1afd980b-7dbc-458c-93f4-2fffdfee72cf")>
INFO     test_case:base_page.py:547 连接设备id locator: ('id', 'android:id/title')
INFO     test_case:base_page.py:527 元素描述为: '知道了' alert
INFO     test_case:base_page.py:535 web_elem: <appium.webdriver.webelement.WebElement (session="96a97253-fc82-4018-96a3-12e7f8132934", element="6b354cc2-0dbe-48ab-bc6f-a75eb8465d20")>
INFO     test_case:base_page.py:547 '知道了' alert locator: ('id', 'com.mega.carsettings:id/tv_sure')
INFO     test_case:base_page.py:527 元素描述为: 配对失败alert
ERROR    test_case:base_page.py:555 元素 配对失败alert 的表达式 ('id', 'com.mega.carsettings:id/tv_title') 未定位到: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:75:1)
    at /Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:92:1
    at flush (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/_microtask.js:18:1)
    at process._tickCallback (internal/process/next_tick.js:61:11)
INFO     test_case:base_page.py:558 错误截图为: /Users/yuxiang/PycharmProjects/chery_app_test/logs/imgs/2023-06-15-13-25-21.png
INFO     test_case:conftest.py:212 正在关闭驱动
INFO     test_case:conftest.py:214 关闭驱动成功！