{"name": "test_connect_error_passwd_01[error_passwd0]", "status": "broken", "statusDetails": {"message": "AttributeError: 'bool' object has no attribute 'send_keys'", "trace": "self = <test_wifi.TestWiFi object at 0x1047f5160>\nerror_passwd = ('AAAAA', 'yx201308', '密码错误')\ninit_wifi = <pages.wifi_page.WiFiPage object at 0x104a8ec10>\n\n    @pytest.mark.flaky(reruns=3)\n    @pytest.mark.error_passwd\n    @pytest.mark.parametrize('error_passwd', wifi_error_data)\n    def test_connect_error_passwd_01(self, error_passwd, init_wifi):\n        \"\"\"\n        密码错误，wifi连接失败测试用例\n        :param error_passwd:\n        :param init_wifi:\n        :return:\n        \"\"\"\n        wifi_page = init_wifi\n        name = error_passwd[0]\n        passwd = error_passwd[1]\n        error_toast = error_passwd[2]\n        if not wifi_page.wifi_button_property:\n            wifi_page.wifi_switch_widget_elem.click()\n        wifi_page.wifi_arrow_elem.click()\n    \n        sleep(2)\n        wifi_page.wifi_name(name).click()\n>       wifi_page.send_password(passwd)\n\ntests/test_wifi.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.wifi_page.WiFiPage object at 0x104a8ec10>, password = 'yx201308'\n\n    def send_password(self, password):\n        \"\"\"\n        输入密码\n        :param password:\n        :return:\n        \"\"\"\n>       return self.password_input_elem.send_keys(password)\nE       AttributeError: 'bool' object has no attribute 'send_keys'\n\npages/wifi_page.py:46: AttributeError"}, "description": "\n        密码错误，wifi连接失败测试用例\n        :param error_passwd:\n        :param init_wifi:\n        :return:\n        ", "attachments": [{"name": "log", "source": "5b2c1d08-9875-4862-91f3-a0e26f3d774a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "error_passwd", "value": "('AAAAA', 'yx201308', '密码错误')"}], "start": 1687919887715, "stop": 1687919902303, "uuid": "aa0413f2-59ff-4f42-b1c5-5b1b9a84bf44", "historyId": "9fb8d6087f4939d5b052bb7e8374e0d6", "testCaseId": "3b72d5f28a223c6be93a780cb6d18f4c", "fullName": "tests.test_wifi.TestWiFi#test_connect_error_passwd_01", "labels": [{"name": "tag", "value": "error_passwd"}, {"name": "tag", "value": "flaky(reruns=3)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_wifi"}, {"name": "subSuite", "value": "TestWiFi"}, {"name": "host", "value": "yuxiangdeMacBook-Pro.local"}, {"name": "thread", "value": "50755-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_wifi"}]}